/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nbp.ncp.nes.model;

import java.util.Objects;
import com.nbp.ncp.nes.model.AddressBookResponseGroups;
import java.util.ArrayList;
import java.util.List;

/**
 * AddressBookResponse
 */
public class AddressBookResponse {
	private Integer totalAddressCount = null;

	private List<AddressBookResponseGroups> groups = null;

	public AddressBookResponse totalAddressCount(Integer totalAddressCount) {
		this.totalAddressCount = totalAddressCount;
		return this;
	}

	 /**
	 * 총 수신자 이메일 주소 수
	 * @return totalAddressCount
	**/
	public Integer getTotalAddressCount() {
		return totalAddressCount;
	}

	public void setTotalAddressCount(Integer totalAddressCount) {
		this.totalAddressCount = totalAddressCount;
	}

	public AddressBookResponse groups(List<AddressBookResponseGroups> groups) {
		this.groups = groups;
		return this;
	}

	public AddressBookResponse addGroupsItem(AddressBookResponseGroups groupsItem) {
		if (this.groups == null) {
			this.groups = new ArrayList<AddressBookResponseGroups>();
		}
		this.groups.add(groupsItem);
		return this;
	}

	 /**
	 * 수신자 그룹 목록
	 * @return groups
	**/
	public List<AddressBookResponseGroups> getGroups() {
		return groups;
	}

	public void setGroups(List<AddressBookResponseGroups> groups) {
		this.groups = groups;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AddressBookResponse addressBookResponse = (AddressBookResponse) o;
		return Objects.equals(this.totalAddressCount, addressBookResponse.totalAddressCount) &&
				Objects.equals(this.groups, addressBookResponse.groups);
	}

	@Override
	public int hashCode() {
		return Objects.hash(totalAddressCount, groups);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AddressBookResponse {\n");
		
		sb.append("		totalAddressCount: ").append(toIndentedString(totalAddressCount)).append("\n");
		sb.append("		groups: ").append(toIndentedString(groups)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

