/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nbp.ncp.nes.model;

import java.util.Objects;

/**
 * Email 발송상태
 */
public class EmailListResponseEmailStatus {
	private String label = null;

	private String code = null;

	public EmailListResponseEmailStatus label(String label) {
		this.label = label;
		return this;
	}

	 /**
	 * 상태 명
	 * @return label
	**/
	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public EmailListResponseEmailStatus code(String code) {
		this.code = code;
		return this;
	}

	 /**
	 * 상태 코드 (P: 발송준비중, R: 발송준비, I: 발송중, S: 발송성공, F: 발송실패, U: 수신거부, C:발송취소, PF: 일부실패)
	 * @return code
	**/
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmailListResponseEmailStatus emailListResponseEmailStatus = (EmailListResponseEmailStatus) o;
		return Objects.equals(this.label, emailListResponseEmailStatus.label) &&
				Objects.equals(this.code, emailListResponseEmailStatus.code);
	}

	@Override
	public int hashCode() {
		return Objects.hash(label, code);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmailListResponseEmailStatus {\n");
		
		sb.append("		label: ").append(toIndentedString(label)).append("\n");
		sb.append("		code: ").append(toIndentedString(code)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

