/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nbp.ncp.nes.model;

import java.util.Objects;

/**
 * EmailResponseAttachFiles
 */
public class EmailResponseAttachFiles {
	private String fileId = null;

	private String fileName = null;

	private Integer fileSize = null;

	public EmailResponseAttachFiles fileId(String fileId) {
		this.fileId = fileId;
		return this;
	}

	 /**
	 * File ID
	 * @return fileId
	**/
	public String getFileId() {
		return fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public EmailResponseAttachFiles fileName(String fileName) {
		this.fileName = fileName;
		return this;
	}

	 /**
	 * File name
	 * @return fileName
	**/
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public EmailResponseAttachFiles fileSize(Integer fileSize) {
		this.fileSize = fileSize;
		return this;
	}

	 /**
	 * File 크기
	 * @return fileSize
	**/
	public Integer getFileSize() {
		return fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmailResponseAttachFiles emailResponseAttachFiles = (EmailResponseAttachFiles) o;
		return Objects.equals(this.fileId, emailResponseAttachFiles.fileId) &&
				Objects.equals(this.fileName, emailResponseAttachFiles.fileName) &&
				Objects.equals(this.fileSize, emailResponseAttachFiles.fileSize);
	}

	@Override
	public int hashCode() {
		return Objects.hash(fileId, fileName, fileSize);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmailResponseAttachFiles {\n");
		
		sb.append("		fileId: ").append(toIndentedString(fileId)).append("\n");
		sb.append("		fileName: ").append(toIndentedString(fileName)).append("\n");
		sb.append("		fileSize: ").append(toIndentedString(fileSize)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

