/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nbp.ncp.nes.model;

import java.util.Objects;
import com.nbp.ncp.nes.model.FileUploadResponseFiles;
import java.util.ArrayList;
import java.util.List;

/**
 * FileUploadResponse
 */
public class FileUploadResponse {
	private String tempRequestId = null;

	private List<FileUploadResponseFiles> files = new ArrayList<FileUploadResponseFiles>();

	public FileUploadResponse tempRequestId(String tempRequestId) {
		this.tempRequestId = tempRequestId;
		return this;
	}

	 /**
	 * 임시 요청 ID
	 * @return tempRequestId
	**/
	public String getTempRequestId() {
		return tempRequestId;
	}

	public void setTempRequestId(String tempRequestId) {
		this.tempRequestId = tempRequestId;
	}

	public FileUploadResponse files(List<FileUploadResponseFiles> files) {
		this.files = files;
		return this;
	}

	public FileUploadResponse addFilesItem(FileUploadResponseFiles filesItem) {
		this.files.add(filesItem);
		return this;
	}

	 /**
	 *  File 목록
	 * @return files
	**/
	public List<FileUploadResponseFiles> getFiles() {
		return files;
	}

	public void setFiles(List<FileUploadResponseFiles> files) {
		this.files = files;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FileUploadResponse fileUploadResponse = (FileUploadResponse) o;
		return Objects.equals(this.tempRequestId, fileUploadResponse.tempRequestId) &&
				Objects.equals(this.files, fileUploadResponse.files);
	}

	@Override
	public int hashCode() {
		return Objects.hash(tempRequestId, files);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FileUploadResponse {\n");
		
		sb.append("		tempRequestId: ").append(toIndentedString(tempRequestId)).append("\n");
		sb.append("		files: ").append(toIndentedString(files)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

