/*
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nbp.ncp.nes.auth;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import com.nbp.ncp.nes.exception.SdkException;

/**
 * The type Properties file credentials provider.
 */
public class PropertiesFileCredentialsProvider implements CredentialsProvider {
    private final String path;
	private final CredentialsProvider providerDelegate;

    /**
     * Instantiates a new Properties file credentials provider.
     *
     * @param path the path
     */
    public PropertiesFileCredentialsProvider(String path) {
        this.path = path;
		Properties properties = new Properties();
		FileInputStream fileInputStream = null;
		try {
			fileInputStream = new FileInputStream(path);
			properties.load(fileInputStream);
		} catch (IOException e) {
			throw new SdkException("Failed to load credentials from the " + path + " file", e);
		} finally {
			try {
				if (fileInputStream != null) {
					fileInputStream.close();
				}
			} catch (IOException e) {
			}
		}

		Map<String, String> map = new HashMap<>();
		map.put("type", properties.getProperty("type"));
		map.put("apiKey", properties.getProperty("apiKey"));
		map.put("accessKey", properties.getProperty("accessKey"));
		map.put("secretKey", properties.getProperty("secretKey"));
		this.providerDelegate = new MapCredentialsProvider(map);
    }

    public Credentials getCredentials() {
    	return this.providerDelegate.getCredentials();
    }

    public void refresh() {
    }
}
