/*
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nbp.ncp.nes.auth;

import com.uanid.sdk.ncloud.service.util.Utils;

import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

/**
 * The type Properties file credentials provider.
 */
public class PropertiesFileCredentialsProvider implements CredentialsProvider {
	private final CredentialsProvider providerDelegate;

    /**
     * Instantiates a new Properties file credentials provider.
     *
     * @param path the path
     */
    public PropertiesFileCredentialsProvider(String path) {
		Properties properties = Utils.loadPropertiesFromFile(path);

		Map<String, String> map = new HashMap<>();
		map.put("type", properties.getProperty("type"));
		map.put("apiKey", properties.getProperty("apiKey"));
		map.put("accessKey", properties.getProperty("accessKey"));
		map.put("secretKey", properties.getProperty("secretKey"));
		this.providerDelegate = new MapCredentialsProvider(map);
    }

    public Credentials getCredentials() {
    	return this.providerDelegate.getCredentials();
    }

    public void refresh() {
    }
}
