/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.uanid.sdk.ncloud.service.mailer.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AddressBookGenerateRequest
 */
public class AddressBookGenerateRequest {
	private List<AddressBookGenerateRequestGroups> groups = new ArrayList<AddressBookGenerateRequestGroups>();

	public AddressBookGenerateRequest groups(List<AddressBookGenerateRequestGroups> groups) {
		this.groups = groups;
		return this;
	}

	public AddressBookGenerateRequest addGroupsItem(AddressBookGenerateRequestGroups groupsItem) {
		this.groups.add(groupsItem);
		return this;
	}

	 /**
	 * 수신자 이메일 주소를 포함한 수신자 그룹목록
	 * @return groups
	**/
	public List<AddressBookGenerateRequestGroups> getGroups() {
		return groups;
	}

	public void setGroups(List<AddressBookGenerateRequestGroups> groups) {
		this.groups = groups;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AddressBookGenerateRequest addressBookGenerateRequest = (AddressBookGenerateRequest) o;
		return Objects.equals(this.groups, addressBookGenerateRequest.groups);
	}

	@Override
	public int hashCode() {
		return Objects.hash(groups);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AddressBookGenerateRequest {\n");
		
		sb.append("		groups: ").append(toIndentedString(groups)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

