/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.uanid.sdk.ncloud.service.mailer.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * AddressBookDeleteAddressRequest
 */
public class AddressBookDeleteAddressRequest {
	private List<String> emailAddresses = new ArrayList<String>();

	public AddressBookDeleteAddressRequest emailAddresses(List<String> emailAddresses) {
		this.emailAddresses = emailAddresses;
		return this;
	}

	public AddressBookDeleteAddressRequest addEmailAddressesItem(String emailAddressesItem) {
		this.emailAddresses.add(emailAddressesItem);
		return this;
	}

	 /**
	 * Get emailAddresses
	 * @return emailAddresses
	**/
	public List<String> getEmailAddresses() {
		return emailAddresses;
	}

	public void setEmailAddresses(List<String> emailAddresses) {
		this.emailAddresses = emailAddresses;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AddressBookDeleteAddressRequest addressBookDeleteAddressRequest = (AddressBookDeleteAddressRequest) o;
		return Objects.equals(this.emailAddresses, addressBookDeleteAddressRequest.emailAddresses);
	}

	@Override
	public int hashCode() {
		return Objects.hash(emailAddresses);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AddressBookDeleteAddressRequest {\n");
		
		sb.append("		emailAddresses: ").append(toIndentedString(emailAddresses)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

