/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.uanid.sdk.ncloud.service.mailer.model;

import java.util.Objects;

/**
 * 예약발송 여부
 */
public class EmailListResponseReservationStatus {
	private String label = null;

	private String code = null;

	public EmailListResponseReservationStatus label(String label) {
		this.label = label;
		return this;
	}

	 /**
	 * 예약 발송 여부 (예약발송 , 즉시발송)
	 * @return label
	**/
	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public EmailListResponseReservationStatus code(String code) {
		this.code = code;
		return this;
	}

	 /**
	 * 상태 코드 (Y: 예약발송, N: 즉시발송)
	 * @return code
	**/
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmailListResponseReservationStatus emailListResponseReservationStatus = (EmailListResponseReservationStatus) o;
		return Objects.equals(this.label, emailListResponseReservationStatus.label) &&
				Objects.equals(this.code, emailListResponseReservationStatus.code);
	}

	@Override
	public int hashCode() {
		return Objects.hash(label, code);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmailListResponseReservationStatus {\n");
		
		sb.append("		label: ").append(toIndentedString(label)).append("\n");
		sb.append("		code: ").append(toIndentedString(code)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

