/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.uanid.sdk.ncloud.service.mailer.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * 수신자 그룹 조합 필터
 */
public class EmailSendRequestRecipientGroupFilter {
	private Boolean andFilter = false;

	private List<String> groups = null;

	public EmailSendRequestRecipientGroupFilter andFilter(Boolean andFilter) {
		this.andFilter = andFilter;
		return this;
	}

	 /**
	 * AND 조합 여부 (false : OR 조합)
	 * @return andFilter
	**/
	public Boolean isAndFilter() {
		return andFilter;
	}

	public void setAndFilter(Boolean andFilter) {
		this.andFilter = andFilter;
	}

	public EmailSendRequestRecipientGroupFilter groups(List<String> groups) {
		this.groups = groups;
		return this;
	}

	public EmailSendRequestRecipientGroupFilter addGroupsItem(String groupsItem) {
		if (this.groups == null) {
			this.groups = new ArrayList<String>();
		}
		this.groups.add(groupsItem);
		return this;
	}

	 /**
	 * 수신자 그룹명
	 * @return groups
	**/
	public List<String> getGroups() {
		return groups;
	}

	public void setGroups(List<String> groups) {
		this.groups = groups;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmailSendRequestRecipientGroupFilter emailSendRequestRecipientGroupFilter = (EmailSendRequestRecipientGroupFilter) o;
		return Objects.equals(this.andFilter, emailSendRequestRecipientGroupFilter.andFilter) &&
				Objects.equals(this.groups, emailSendRequestRecipientGroupFilter.groups);
	}

	@Override
	public int hashCode() {
		return Objects.hash(andFilter, groups);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmailSendRequestRecipientGroupFilter {\n");
		
		sb.append("		andFilter: ").append(toIndentedString(andFilter)).append("\n");
		sb.append("		groups: ").append(toIndentedString(groups)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

