/*
 * api
 * Cloud Outbound Mailer API<br/>https://mail.test-apigw.ntruss.com/api/v1
 *
 * OpenAPI spec version: 2019-06-20T02:51:35Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.uanid.sdk.ncloud.service.mailer.model;

import java.util.Objects;

/**
 * EmailSendResponse
 */
public class EmailSendResponse {
	private Integer count = null;

	private String requestId = null;

	public EmailSendResponse count(Integer count) {
		this.count = count;
		return this;
	}

	 /**
	 * 발송요청 메일 건수
	 * @return count
	**/
	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public EmailSendResponse requestId(String requestId) {
		this.requestId = requestId;
		return this;
	}

	 /**
	 * 발송요청 ID
	 * @return requestId
	**/
	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmailSendResponse emailSendResponse = (EmailSendResponse) o;
		return Objects.equals(this.count, emailSendResponse.count) &&
				Objects.equals(this.requestId, emailSendResponse.requestId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(count, requestId);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmailSendResponse {\n");
		
		sb.append("		count: ").append(toIndentedString(count)).append("\n");
		sb.append("		requestId: ").append(toIndentedString(requestId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

